export const AGREGAR_TAREA = "AGREGAR_TAREA";

export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const EDITAR_TAREA = "EDITAR_TAREA";
export const ACTIVAR_TAREA = "ACTIVAR_TAREA";
export const COMPLETAR_TAREA = "COMPLETAR_TAREA";
export const REHACER_TAREA = "REHACER_TAREA";	 